# Site settings
title: rollmind
url: "https://rollmind.github.io"
baseurl: ""
description: >
Rollmind Wiki (from https://johngrib.github.io)
이 블로그(위키)는 기계인간 johngrib님의 허락을 얻어 공부 및 위키 작성용으로 포크했습니다.

# My information
email: eyerama@gmail.com
author: rollmind
twitter_username: KwanghoonChoi
github_username: rollmind

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist

permalink: /blog/:year/:month/:day/:title/

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

paginate: 10
paginator_path: "/blog"
paginate_path: "/blog/page:num/"

# Collections
collections:
    wiki:
        output: true
        permalink: /:collection/:path/

# Comment Service

blame: "https://github.com/rollmind/rollmind.github.io/blame/master/_wiki"
edit: "https://github.com/rollmind/rollmind.github.io/edit/master/_wiki"
issue: "https://github.com/rollmind/rollmind.github.io/issues/new"
